# Generated by Django 2.0.7 on 2021-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='available',
            field=models.NullBooleanField(),
        ),
    ]
