# Generated by Django 2.0.7 on 2021-02-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20210131_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('width', models.TextField()),
                ('height', models.TextField()),
                ('artist', models.TextField()),
                ('user', models.TextField()),
            ],
        ),
    ]
