# Generated by Django 3.1.7 on 2021-03-07 18:23

import artwork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_searchparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='images',
            field=models.ImageField(default='AG\\static\x07pp\\images\\default.PNG', upload_to='AG\static\app\images/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
