# Generated by Django 3.1.7 on 2021-03-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_auto_20210307_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='images',
            field=models.ImageField(default='AG\\images\\default.PNG', upload_to=''),
        ),
    ]
