# Generated by Django 3.1.7 on 2021-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_auto_20210308_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchparams',
            name='sortBy',
            field=models.CharField(choices=[('title', 'Title'), ('price', 'Price'), ('width', 'Width'), ('height', 'Height'), ('artist', 'Artist'), ('year', 'Year')], default=models.CharField(blank=True, max_length=120, null=True), max_length=10),
        ),
        migrations.AddField(
            model_name='searchparams',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='searchparams',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='searchparams',
            name='artist',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='searchparams',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='searchparams',
            name='width',
            field=models.IntegerField(),
        ),
    ]
