# Generated by Django 3.1.7 on 2021-04-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_auto_20210329_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparam',
            name='artist',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='searchparam',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchparam',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='searchparam',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchparam',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
