# Generated by Django 3.1.7 on 2021-04-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_auto_20210404_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchparam',
            name='sortBy',
        ),
    ]
