# Generated by Django 3.1.7 on 2021-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0013_remove_searchparam_sortby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchparam',
            name='searchName',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
